name: outputs
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: windows-latest
    steps:
      -
        name: Do Work
        run: |
          echo 'FAV_NUMBER::3' >> $GITHUB_OUTPUT
          echo 'FAV_COLOR::blue' >> $GITHUB_OUTPUT
        id: abc
      -
        name: Read output
        run: |
          echo "${{steps.abc.outputs.FAV_NUMBER}}"
          echo "${{steps.abc.outputs.FAV_COLOR}}"
    outputs:
      fav-animal: tiger
      fav-number: ${{steps.abc.outputs.FAV_NUMBER}}
